package ServerInterface;


/**
* ServerInterface/CommonInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Project/Comp6231A2/src/ServerInterface.idl
* Saturday, July 6, 2019 4:09:45 o'clock PM EDT
*/

public interface CommonInterface extends CommonInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CommonInterface
