package ServerInterface;


/**
* ServerInterface/CommonInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Project/Comp6231A2/src/ServerInterface.idl
* Saturday, July 6, 2019 4:09:45 o'clock PM EDT
*/

abstract public class CommonInterfaceHelper
{
  private static String  _id = "IDL:ServerInterface/CommonInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerInterface.CommonInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerInterface.CommonInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerInterface.CommonInterfaceHelper.id (), "CommonInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerInterface.CommonInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CommonInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerInterface.CommonInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerInterface.CommonInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerInterface.CommonInterface)
      return (ServerInterface.CommonInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerInterface._CommonInterfaceStub stub = new ServerInterface._CommonInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerInterface.CommonInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerInterface.CommonInterface)
      return (ServerInterface.CommonInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerInterface._CommonInterfaceStub stub = new ServerInterface._CommonInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
