package FEInterface;


/**
 * FEInterface/CommonInterface.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Project/Comp6231Project/src/FEInterface.idl
 * Friday, July 26, 2019 9:02:42 o'clock PM EDT
 */

public interface CommonInterface extends CommonInterfaceOperations,
        org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface CommonInterface
