package FEInterface;

/**
 * FEInterface/CommonInterfaceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Project/Comp6231Project/src/FEInterface.idl
 * Friday, July 26, 2019 9:02:42 o'clock PM EDT
 */

public final class CommonInterfaceHolder implements org.omg.CORBA.portable.Streamable {
    public FEInterface.CommonInterface value = null;

    public CommonInterfaceHolder() {
    }

    public CommonInterfaceHolder(FEInterface.CommonInterface initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = FEInterface.CommonInterfaceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        FEInterface.CommonInterfaceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return FEInterface.CommonInterfaceHelper.type();
    }

}
