package FEInterface;


/**
 * FEInterface/CommonInterfaceHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Project/Comp6231Project/src/FEInterface.idl
 * Friday, July 26, 2019 9:02:42 o'clock PM EDT
 */

abstract public class CommonInterfaceHelper {
    private static String _id = "IDL:FEInterface/CommonInterface:1.0";
    private static org.omg.CORBA.TypeCode __typeCode = null;

    public static void insert(
            org.omg.CORBA.Any a,
            FEInterface.CommonInterface that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static FEInterface.CommonInterface extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode =
                    org.omg.CORBA.ORB.init().create_interface_tc(FEInterface.CommonInterfaceHelper.id(), "CommonInterface");
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static FEInterface.CommonInterface read(org.omg.CORBA.portable.InputStream istream) {
        return narrow(istream.read_Object(_CommonInterfaceStub.class));
    }

    public static void write(
            org.omg.CORBA.portable.OutputStream ostream,
            FEInterface.CommonInterface value) {
        ostream.write_Object((org.omg.CORBA.Object) value);
    }

    public static FEInterface.CommonInterface narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof FEInterface.CommonInterface)
            return (FEInterface.CommonInterface) obj;
        else if (!obj._is_a(id()))
            throw new org.omg.CORBA.BAD_PARAM();
        else {
            org.omg.CORBA.portable.Delegate delegate =
                    ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            FEInterface._CommonInterfaceStub stub =
                    new FEInterface._CommonInterfaceStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

    public static FEInterface.CommonInterface unchecked_narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof FEInterface.CommonInterface)
            return (FEInterface.CommonInterface) obj;
        else {
            org.omg.CORBA.portable.Delegate delegate =
                    ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            FEInterface._CommonInterfaceStub stub =
                    new FEInterface._CommonInterfaceStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

}
